### ISSUE TITLE
Formulas do not work

### ISSUE THREAD

**Issue by f-rey** [andrenarchy/talk-2013-01-projections#1]
Presentation does not display formulas properly when opened in browser. Instead it shows LaTeX-code, e.g. \perp, \lambda, ( ), ...

Tested on Macbook Pro running OS X 10.10 using Safari, Opera and Chrome.
(p.s. it would be great if you could fix this and/or provide an pdf version of your presentation. thanks as lot!)

**Comment by andrenarchy** [comment]
Thanks for your report! Do you mean the presentation [here](http://andrenarchy.github.io/talk-2013-01-projections/)? I just checked it on my machine with Chromium 39 and Firefox 34 on Ubuntu and it works fine. Can you check if the JavaScript console spits out any error messages?

I noticed that disabling cookies also disables other stuff that breaks MathJax... have you disabled cookies?

**Comment by f-rey** [comment]
Cookies and Javascript is enabled.

The JS console says:
GET https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
Uncaught ReferenceError: MathJax is not defined

Just tested it with my IOS 8.1 device — same problem.
Do I need to install MathJax? I thought it would be provided by the server…

Thanks for your help!
Felix

## 

Felix Rey
MSc., Ph.D. Student

ETH Zurich
Automatic Control Laboratory
Physikstrasse 3, ETL I 13
8092 Zurich
Switzerland

Phone:   +41 44 632 0423
Fax:     +41 44 632 1211
Email:   felix.rey@control.ee.ethz.chmailto:felix.rey@control.ee.ethz.ch

On 14 Jan 2015, at 12:28, André Gaul <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for your report! Do you mean the presentation herehttp://andrenarchy.github.io/talk-2013-01-projections/? I just checked it on my machine with Chromium 39 and Firefox 34 on Ubuntu and it works fine. Can you check if the JavaScript console spits out any error messages?

I noticed that disabling cookies also disables other stuff that breaks MathJax... have you disabled cookies?

**Comment by f-rey** [comment]
Oh and… Yes, I mean that presentation.

Thanks again.
Felix

## 

Felix Rey
MSc., Ph.D. Student

ETH Zurich
Automatic Control Laboratory
Physikstrasse 3, ETL I 13
8092 Zurich
Switzerland

Phone:   +41 44 632 0423
Fax:     +41 44 632 1211
Email:   felix.rey@control.ee.ethz.chmailto:felix.rey@control.ee.ethz.ch

On 14 Jan 2015, at 13:18, Rey Felix <felix.rey@control.ee.ethz.ch<mailto:felix.rey@control.ee.ethz.ch>> wrote:

Cookies and Javascript is enabled.

The JS console says:
GET https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
Uncaught ReferenceError: MathJax is not defined

Just tested it with my IOS 8.1 device — same problem.
Do I need to install MathJax? I thought it would be provided by the server…

Thanks for your help!
Felix

## 

Felix Rey
MSc., Ph.D. Student

ETH Zurich
Automatic Control Laboratory
Physikstrasse 3, ETL I 13
8092 Zurich
Switzerland

Phone:   +41 44 632 0423
Fax:     +41 44 632 1211
Email:   felix.rey@control.ee.ethz.chmailto:felix.rey@control.ee.ethz.ch

On 14 Jan 2015, at 12:28, André Gaul <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for your report! Do you mean the presentation herehttp://andrenarchy.github.io/talk-2013-01-projections/? I just checked it on my machine with Chromium 39 and Firefox 34 on Ubuntu and it works fine. Can you check if the JavaScript console spits out any error messages?

I noticed that disabling cookies also disables other stuff that breaks MathJax... have you disabled cookies?

**Comment by andrenarchy** [comment]
It should just work™. :smiley:

I changed the URL where MathJax is loaded from. Can you check again? Please clear your browser cache before...

**Comment by f-rey** [comment]
It works!
Thanks a lot!

Very cool presentation by the way. (I mean the fact that its browser-based and having a modern appearance.)
HTML5 does actually seem to rock.

Best,
Felix

## 

Felix Rey
MSc., Ph.D. Student

ETH Zurich
Automatic Control Laboratory
Physikstrasse 3, ETL I 13
8092 Zurich
Switzerland

Phone:   +41 44 632 0423
Fax:     +41 44 632 1211
Email:   felix.rey@control.ee.ethz.chmailto:felix.rey@control.ee.ethz.ch

On 14 Jan 2015, at 13:28, André Gaul <notifications@github.com<mailto:notifications@github.com>> wrote:

It should just work™. [:smiley:]

I changed the URL where MathJax is loaded from. Can you check again? Please clear your browser cache before...

**Comment by andrenarchy** [comment]
Thanks for reporting again! Yeah, HTML5 definitely rocks. Hard. ;)

Btw, if you're interested in projections and applications of them: I just added a link to my [PhD thesis](https://github.com/andrenarchy/phdthesis) in the readme. It has contains much more details about the results in this talk.
